name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      TEST_ANTHROPIC_API_KEY: ${{ secrets.TEST_ANTHROPIC_API_KEY }}
      TEST_OPENAI_API_KEY: ${{ secrets.TEST_OPENAI_API_KEY }}
      TEST_AZURE_API_KEY: ${{ secrets.TEST_AZURE_API_KEY }}
      TEST_AZURE_API_BASE: ${{ secrets.TEST_AZURE_API_BASE }}
      TEST_AZURE_API_VERSION: ${{ secrets.TEST_AZURE_API_VERSION }}
      TEST_GEMINI_API_KEY: ${{ secrets.TEST_GEMINI_API_KEY }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
    
    - name: Install dependencies
      run: |
        uv sync
    
    - name: Run tests
      run: |
        uv run pytest tests/ -v 